### PR TITLE
calculate percent by owner category

### PR DESCRIPTION
**Pull request by maggiesu0725**

### CODE REVIEW

**Comment by maggiesu0725** [comment]
@rpitingolo @lhendey table 1C ready for review

**Comment by rpitingolo** [comment]
@maggiesu0725 the part at the bottom under "percent of units with 3+ bedrooms by property type " doesn't look right. Can you take another look?

**Comment by maggiesu0725** [comment]
@rpitingolo pushed minor bug fix, in the same section, the code to generate flag for condo units is not working (if condo=1 or singlefamily=1 then combined=1; else combined=0;) any idea why?

**Comment by rpitingolo** [comment]
@maggiesu0725 the lines of code above I think are not calculating correctly. ui_proptype is a character variable but you have it coded as numeric. Also when I run a frequency on the file the only two codes that show up are 10 and 11. Where did you get the codes from for this?

**Comment by lhendey** [comment]
@maggiesu0725 - please change the class statements in the proc summaries to by statements as you did on the affordability program. the flag for sf vs. condo would best be created before the summaries and just included in there. 
if ui_proptype="10" then singlefamily=1; else singlefamily=0; 
if ui_proptype="11" then condo=1; else condo=0; 

This file already has only SF/condo. I think you were looking at the values for usecode instead of ui_proptype (which is a 3 character var - would need " " around the values). cc @rpitingolo

**Comment by maggiesu0725** [comment]
@rpitingolo @lhendey  ready for a final review, I used this code to populate  table 1C

**Comment by rpitingolo** [comment]
@maggiesu0725 thanks. I'll review. @lhendey

**Comment by lhendey** [comment]
@maggiesu0725 - i'm reviewing this now for @rpitingolo

**Comment by lhendey** [comment]
@maggiesu0725 - okay to merge. please update table 1c i made a few changes that will affect the output. the sf vs. condo numbers are in the main export now.

**Pull request merged**
