### PR TITLE
Created Program to Count LIHTC and IZ Units by Bedroom Size

### PR DESCRIPTION
**Pull request by mcohenui**
@lhendey @Woliver01 Here is the program to create the unit count by bedroom size for LIHTC and IZ. In order for this program to run, the program reading in the DMPED Pipeline Data will need to be approved, merged, and run on L to create the appropriate data sets. Leah, I have tagged you on that pull request.

### CODE REVIEW

**Comment by mcohenui** [comment]
@lhendey Code that compiles the unit count data for the large units table.

**Comment by lhendey** [comment]
@mcohenui - i had a little trouble reviewing. do we need to do anything with the geocode output? it didn't look like all the tabulates were printing? (can we clean this up to add titles to them?) .

**Comment by mcohenui** [comment]
@ptatian Current status of issue #13 . Leah asked me to clean up the tabulations. I submitted new code, should be ready for review.

**Comment by ptatian** [comment]
Thanks, @mcohenui. I will take a look.

**Comment by ptatian** [comment]
@mcohenui I had a problem with Prog\LIHTC_IZ_Unit_Count.sas. It is looking for a DMPED.IZ_BED_Pipeline_2018 data set that does not exist. Do you know where this data set comes from?

**Comment by mcohenui** [comment]
@ptatian Sorry about the confusion. The task originally was to count the DMPED data. I changed the name of the program when the other subsidized unit counts were added in. The LIHTC_IZ_Unit_Count.sas and Sec8 with bedroom and ward.sas programs were replaced by the Large_unit_subsidy_count.sas program.

**Comment by ptatian** [comment]
Thanks, @mcohenui. So, I only need to worry about Large_unit_subsidy_count.sas, yes? 

If the other programs are now obsolete, I would probably recommend we delete them.

**Comment by mcohenui** [comment]
@ptatian that is correct. I had kept them around for reference, but I can go ahead and delete them now. Should I submit a new pull request now, or after your review?

**Comment by ptatian** [comment]
@mcohenui Yes, you can go ahead and commit/push the file deletions. You don't need to do a new pull request. The new commit will automatically be added to the existing pull request.

**Comment by mcohenui** [comment]
@ptatian done

**Comment by ptatian** [comment]
@mcohenui Do we know what the drop_ field means in the IZ data?

**Comment by mcohenui** [comment]
@ptatian It is an additional unit size variable "Number of Bedrooms Per IZ Definition". The variable I kept in is per the Certificate of Inclusionary Zoning Compliance. I am not sure how the IZ variable differs, but I dropped it as it is included in only 24 of the observations and only 7 of those conflicted with the CIZC count.

**Pull request merged**
