### PR TITLE
Develop #53

### PR DESCRIPTION
**Pull request by rpitingolo**
@lhendey can you please review and if you need to fix the coding error you mentioned before please push that? Otherwise, the 2B is ready except for that potential fix.

### CODE REVIEW

**Comment by lhendey** [comment]
@rpitingolo it's not running correctly (errors in log). I adjusted my code. maybe ask @ptatian for review after? I'm jumping on a call for an hour.

**Comment by rpitingolo** [comment]
@lhendey the comment you added inside the macro wasn't in the /* */ format and commented out some of the code and caused errors. I've fixed it. 

@ptatian can you please do a final review?

**Comment by ptatian** [comment]
@rpitingolo @lhendey Yes, I'll review.

**Comment by rpitingolo** [comment]
@ptatian thanks

**Comment by lhendey** [comment]
@ptatian - i saw a review was requested of me? just double checking you are doing the review.

**Comment by ptatian** [comment]
@lhendey Yes, sorry. I removed then added you as reviewer inadvertently. I'm reviewing.

**Comment by ptatian** [comment]
@rpitingolo The %KidsBedroomsNeeded() macro is generating some uninitialized variable messages. Not sure whether this is a problem but you should take a look at it. 

`NOTE: Variable girl6 is uninitialized.`

`NOTE: Variable boy5 is uninitialized.`

**Comment by rpitingolo** [comment]
@ptatian thanks for reviewing. I'll take a look at that uninitialized variable message now. @lhendey

**Comment by rpitingolo** [comment]
@ptatian the uninitialized variable warning is happening because when you run for owner-occupied only there aren't any households with 6 girls or 5 boys. It's not causing any errors or problems regardless. @lhendey

**Pull request merged**
