### PR TITLE
Analysis #14 - code to create annual file

### PR DESCRIPTION
**Pull request by lhendey**

### CODE REVIEW

**Comment by lhendey** [comment]
@ptatian - can you review? The goal would be that these files will enable someone to write code to fill out these tables https://urbanorg.app.box.com/file/302362084379

**Comment by lhendey** [comment]
@ptatian can you review in the morning?

**Comment by ptatian** [comment]
@lhendey Yes

**Comment by lhendey** [comment]
@ptatian  thanks. i added the total. will merge and close issue now.

**Pull request merged**
