### PR TITLE
Develop #4

### PR DESCRIPTION
**Pull request by Woliver01**
@NeighborhoodInfoDC/review @rpitingolo added the variables that I could find.

### CODE REVIEW

**Comment by rpitingolo** [comment]
@Woliver01 thanks. I've reviewed. The next step is to add variables from the tract data that we don't have in these summary files. I've sent you an invite to discuss.

**Comment by Woliver01** [comment]
@rpitingolo please review. Also the ncdb_sum_city and ward meta data don't have variables for 0bdrms prior to 2000.
file:///L:/Metadata/meta_ncdb_ncdb_sum_city.html
file:///L:/Metadata/meta_ncdb_ncdb_sum_wd12.html

**Comment by rpitingolo** [comment]
@Woliver01 thanks. You have a typo it should be statecd rather than stated. Please make sure to check the output file to make sure it's showing up and the log which will give you a hint as to what's going wrong. 

Please go ahead and add in the owner occupied units in your data step. 

For 0bdrms prior to 2000 we will need to pull them out of the ncdb_master_update file as well.

**Comment by rpitingolo** [comment]
@lhendey - @Woliver01 is working on filling out table 1a right now. I am going to leave this pull request open in case we need any edits. Once we're happy with the table I will merge the branch.

**Comment by lhendey** [comment]
Please address @rpitingolo @Woliver01  the numbers on the rent levels worksheet should all be %. Row 5 for example should be numerator=3+ bedrooms unit that rent for 500 or less and denominator = all 3+ bed room renter occupied units

**Comment by rpitingolo** [comment]
@lhendey OK. I'll take a look this morning. @Woliver01

**Comment by rpitingolo** [comment]
@lhendey should the values in row 4 and 10 be numbers or percents? If percents then it might look  to the untrained eye like the numbers add up to >100%

**Comment by rpitingolo** [comment]
@Woliver01 I've exported a new csv to L:\Libraries\DMPED\Prog\table1a_raw_10jul18.csv

Can you please update table 1a? Please be careful on the "rent levels" tab as I deleted the data that was previously in rows 4 and 10 and the values that were previously numbers are now percents. 

@lhendey

**Comment by lhendey** [comment]
@rpitingolo - this isn't calculating correctly ch_5brall_2000_to_2012_16 (assuming the numbers in the table are right). 
--

**Comment by rpitingolo** [comment]
@lhendey are you referencing the new csv I just output? The previous version had an error in the calculation.

**Comment by lhendey** [comment]
@rpitingolo - no old output. did you fix the other change ones too? They are wrong - wrong year on denominator. 
pct_ch_tot_2000_to_2006_10 = (numhsgunits_2006_10 - numhsgunits_2000) / numhsgunits_2006_10;
	pct_ch_3p_2000_to_2006_10 = (numhsgunits3plusbd_2006_10 - numhsgunits3plusbd_2000) / numhsgunits3plusbd_2006_10;

	pct_ch_tot_2006_10_to_2012_16 = (numhsgunits_2012_16 - numhsgunits_2006_10) / numhsgunits_2012_16;
	pct_ch_3p_2006_10_to_2012_16 = (numhsgunits3plusbd_2012_16 - numhsgunits3plusbd_2006_10) / numhsgunits3plusbd_2012_16;

**Comment by rpitingolo** [comment]
@lhendey i fixed the ch_5brall_2000_to_2012_16 var before, i just fixed the denominators.

**Comment by rpitingolo** [comment]
@lhendey ready for re-review. I saved the updated 1A on Box but there was a conflict so it saved as a copy, I think.

**Comment by lhendey** [comment]
@rpitingolo looks fine. do you want to go ahead and merge/close? I moved a "data" sheet into 1A and updated the data from the new file. you can delete your copy.

**Comment by rpitingolo** [comment]
@lhendey thanks. yes.

**Pull request merged**
