### PR TITLE
Develop #49

### PR DESCRIPTION
**Pull request by rpitingolo**
@lhendey can you review? Is this what you wanted? Should I add a finalize dataset?

### CODE REVIEW

**Comment by lhendey** [comment]
@rpitingolo - no need to finalize - i think you can just add a summary for the city level, transpose and output a csv that we can copy and add to table 1a.

**Comment by rpitingolo** [comment]
@lhendey ok, so it needs to be transposed as well, right? So that it matches the format of the raw data in 1a now?

**Comment by lhendey** [comment]
@rpitingolo yes.

**Comment by rpitingolo** [comment]
@lhendey got it. thanks.

**Comment by lhendey** [comment]
@rpitingolo looks good. please merge and close the issue.

**Pull request merged**
